-- ==========================================================================
-- SCRIPT DE CONFIGURAÇÃO DE NOTIFICAÇÕES & CRON (MKT-002)
-- Execute este script no SQL Editor do seu painel Supabase.
-- ==========================================================================

-- 1. Criação da tabela de inscrições de push (caso não exista)
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    endpoint text UNIQUE NOT NULL,
    p256dh text,
    auth text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilita RLS (Row Level Security) na tabela
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Remove policies antigas se existirem para evitar conflito
DROP POLICY IF EXISTS "Users can manage their own subscriptions" ON push_subscriptions;

-- Cria política permitindo que usuários gerenciem apenas suas próprias inscrições
CREATE POLICY "Users can manage their own subscriptions"
ON push_subscriptions
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 2. Habilita pg_cron e define o agendamento
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Remove agendamento antigo se existir
SELECT cron.unschedule('streak-reminder-daily');

-- Agenda chamada diária às 22h00 (horário de Brasília se o servidor estiver em UTC/GMT-3, caso contrário ajuste o cron)
-- Substitua apenas '<SERVICE_ROLE_KEY>' pela chave secreta do seu projeto (encontrada em Settings -> API -> service_role key no painel do Supabase).
SELECT cron.schedule(
    'streak-reminder-daily',
    '0 22 * * *',
    $$
    SELECT net.http_post(
        url := 'https://ppsqvppnunzagxqruoqf.supabase.co/functions/v1/send-push',
        headers := '{"Content-Type": "application/json", "Authorization": "Bearer <SERVICE_ROLE_KEY>"}'::jsonb,
        body := '{"action": "trigger_all_reminders"}'::jsonb
    );
    $$
);
